ctrl_plane:
  hosts:
    10.37.33.23:
      ansible_ssh_private_key_file: ~/.ssh/blackteam
      ansible_user: ubuntu
  vars:
    hostname: ctrl-plane
database:
  hosts:
    10.37.33.15:
      ansible_ssh_private_key_file: ~/.ssh/blackteam
      ansible_user: database
  vars:
    hostname: database
firewall:
  hosts:
    10.37.31.4
  vars:
    hostname: firewall
graylog:
  hosts:
    10.37.32.10:
      ansible_ssh_private_key_file: ~/.ssh/blackteam
      ansible_user: graylog
      ansible_become_password: "graylog"
  vars:
    hostname: graylog

nginx:
  hosts:
    10.37.32.4:
      ansible_ssh_private_key_file: ~/.ssh/blackteam
      ansible_user: rocky
  vars:
    hostname: nginx
node_1:
  hosts: 
    10.37.33.19:
      ansible_ssh_private_key_file: ~/.ssh/blackteam
      ansible_user: ubuntu
  vars:
    hostname: node-1
node_2:
  hosts:
    10.37.33.18:
      ansible_ssh_private_key_file: ~/.ssh/blackteam
      ansible_user: ubuntu
  vars:
    hostname: node-2
node_3:
  hosts:
    10.37.33.20:
      ansible_ssh_private_key_file: ~/.ssh/blackteam
      ansible_user: ubuntu
  vars:
    hostname: node-3
windows_ca:
  hosts:
    10.37.32.14:
      ansible_user: Administrator
      ansible_become_password: "Thunderpoint789*"
  vars:
    hostname: ca-01
windows_dc:
  hosts:
    10.37.33.24:
      ansible_user: Administrator
  vars:
    hostname: dc-01
windows_workstation:
  hosts:
    10.37.33.26:
      ansible_user: Administrator
      ansible_become_password: "Thunderpoint789*"
  vars:
    hostname: win01

# scorestack:
#   hosts: 
#     10.37.31.3:
#       ansible_ssh_private_key_file: ../documentation/black_team/black-team
#       ansible_user: ubuntu
#       ansible_become_password: "ubuntu"
#   vars:
#     hostname: scorestack