---
- name: Download Teleport GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.teleport.dev/gpg
    dest: /usr/share/keyrings/teleport-archive-keyring.asc
    mode: '0644'
  tags:
    - teleport

- name: Add Teleport's APT repository
  ansible.builtin.apt_repository:
    repo: >
      deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc]
      https://apt.releases.teleport.dev/debian
      {{ ansible_distribution_release }} stable/v15
    state: present
  tags:
    - teleport

- name: Install Teleport
  ansible.builtin.apt:
    name: teleport
    state: present
    update_cache: true
  tags:
    - teleport
