---
- name: NTP - Update MaxPosPhaseCorrection
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\W32Time\Config
    name: MaxPosPhaseCorrection
    data: 0xFFFFFFFF
    type: dword
    state: present

# tammy
- name: NTP - Ensure w32time service is enabled
  ansible.windows.win_service:
    name: w32time
    start_mode: auto
    state: started

- name: NTP - Set NTP Servers
  ansible.windows.win_shell: 'w32tm /config /manualpeerlist:"{{ ntp_servers }}" /syncfromflags:manual /reliable:yes /update'

- name: NTP - Stop w32time service
  ansible.windows.win_service:
    name: w32time
    state: stopped

- name: NTP - Start w32time service
  ansible.windows.win_service:
    name: w32time
    state: started

- name: NTP - Resync rediscover
  win_shell: 'w32tm /resync /rediscover'

- name: NTP - Resync force
  win_shell: 'w32tm /resync /force'

- name: NTP - Set Server Time Zone to Eastern Standard Time
  community.windows.win_timezone:
    timezone: Eastern Standard Time
