---
- name: restart falco
  ansible.builtin.systemd:
    name: falco-modern-bpf
    state: restarted
    daemon_reload: true

- name: restart falcosidekick
  ansible.builtin.systemd:
    name: falcosidekick
    state: restarted
    daemon_reload: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
