kind: role
version: v7
metadata:
  name: employee
  description: General access granted to all ChefOps employees to perform job actions
spec:
  options:
    create_host_user_mode: keep
  allow:
    app_labels:
      qos: development
    logins:
      - '{{internal.logins}}'
    node_labels:
      qos: development
