services:
  grafana:
    image: grafana/grafana:9.5.3
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=3000
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "9000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
    networks:
      - grafanet
    depends_on:
      - mimir
      - loki

  nginx:
    image: nginx:trixie-perl
    container_name: nginx
    restart: unless-stopped
    ports:
      - "9009:9009"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - grafanet
    depends_on:
      - loki

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-prometheus-exporter
    restart: unless-stopped
    command: 
      - -nginx.scrape-uri=http://nginx:8080/stub_status
    ports:
      - "9152:9113"
    networks:
      - grafanet
    depends_on:
      - nginx
  mimir:
    image: grafana/mimir:2.10.0
    container_name: mimir
    restart: unless-stopped
    command: 
      - -config.file=/etc/mimir/mimir.yaml
    ports:
      - "127.0.0.1:9008:9009"
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir/mimir.yaml:ro
      - mimir-data:/mimir
    networks:
      - grafanet
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    restart: unless-stopped
    command: 
      - -config.file=/etc/loki/loki.yaml
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./loki/loki.yaml:/etc/loki/loki.yaml:ro
      - loki-data:/loki
    networks:
      - grafanet

volumes:
  grafana-data:
  mimir-data:
  loki-data:
networks:
  grafanet:
    driver: bridge

