team_public_domain: 'placebo-pharma.com'

team_address:
  # firewall_public: "10.255.{{ team }}.254"
  # firewall_private: "10.0.{{ (team * 4) + 3 }}.254"
  # firewall_dmz: "10.0.{{ (team * 4) }}.254"
  # ctrl_plane: "10.0.{{ (team * 4) + 2 }}.255"
  # database: "10.0.{{ (team * 4) + 3 }}.192"
  # graylog: "10.0.{{ (team * 4) }}.247"
  # nginx: "10.0.{{ (team * 4) }}.200"
  # node_1: "10.0.{{ (team * 4) + 3 }}.0"
  # node_2: "10.0.{{ (team * 4) + 3 }}.77"
  # node_3: "10.0.{{ (team * 4) + 2 }}.5"
  # windows_ca: "10.37.32.14"
  # windows_dc: "10.37.33.24"
  # windows_workstation: "10.37.33.26"
  # windows_ca2: "10.37.32.15"
  # windows_dc2: "10.37.33.33"
  # windows_workstation2: "10.37.33.36"
  windows_ca3: "10.37.32.16"
  windows_dc3: "10.37.33.39"
  windows_workstation3: "10.37.33.38"
