database:
  hosts:
    10.37.33.43:
      ansible_user: database
      ansible_ssh_private_key_file: ../../../../documentation/black_team/black-team
      team: 2
      dns_server_override: "10.37.1.1"
      search_domain_override: "proxmox.internal"
  vars:
    hostname: database
    
firewall:
  hosts:
  vars:
    hostname: firewall
grafana:
  hosts:
    10.37.32.22:
      ansible_user: grafana
      ansible_ssh_private_key_file: ../../../../documentation/black_team/black-team
      team: 2
      dns_server_override: "10.37.1.1"
      search_domain_override: "proxmox.internal"
  vars:
    hostname: grafana

falco:
  hosts:
    10.37.33.45:
      ansible_user: rocky
      ansible_ssh_private_key_file: ../../../../documentation/black_team/black-team
      team: 2
      dns_server_override: "10.37.1.1"
      search_domain_override: "proxmox.internal"
  vars:
    hostname: rocky

wordpress:
  hosts:
    10.37.32.23:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ../../../../documentation/black_team/black-team
      team: 2
      dns_server_override: "10.37.1.1"
      search_domain_override: "proxmox.internal"
  vars:
    hostname: ubuntu

teleport:
  hosts:
    10.37.32.20:
      ansible_ssh_private_key_file: ../../../../documentation/black_team/black-team
      ansible_user: teleport
      team: 2
      dns_server_override: "10.37.1.1"
      search_domain_override: "proxmox.internal"
  vars:
    hostname: teleport

semaphore:
  hosts:
    10.37.33.44:
      ansible_user: semaphore
      ansible_ssh_private_key_file: ../../../../documentation/black_team/black-team
      team: 2
      dns_server_override: "10.37.1.1"
      search_domain_override: "proxmox.internal"
  vars:
    hostname: semaphore

win-pos:
  hosts:
    10.37.30.2:
      ansible_user: Administrator
      ansible_password: "Thunderpoint789*"
      team: 2
  vars:
    hostname: xampp