---
- name: Reload sysctl
  ansible.builtin.command:
    cmd: /sbin/sysctl -p
  become: true

- name: Restart Graylog Server
  ansible.builtin.systemd:
    name: graylog-server
    state: restarted

- name: Restart Graylog Data Node
  ansible.builtin.systemd:
    name: graylog-datanode
    state: restarted
