---
- name: Copy Pipeline Files
  ansible.builtin.template:
    src: "templates/pipeline/{{ item }}"
    dest: "/home/ubuntu/pipeline/{{ item }}"
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  loop:
    - etcher/ingress.yaml
    - etcher/configmap.yaml
    - etcher/deployment.yaml
    - grapher/ingress.yaml
    - grapher/configmap.yaml
    - grapher/deployment.yaml
    - recorder/ingress.yaml
    - recorder/configmap.yaml
    - recorder/deployment.yaml
  vars:
    team_id: "{{ hostvars[inventory_hostname]['team'] }}"
  tags:
    - services
    - pipeline

- name: Pipeline InfluxDB write credentials
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: influxdb-credentials
        namespace: pipeline
      data:
        INFLUX_BUCKET: "{{ 'PlaceboPharmaData' | b64encode }}"
        INFLUX_ORG: "{{ 'PlaceboPharma' | b64encode }}"
        INFLUXDB_TOKEN: "{{ lookup('file', '../../pre/database/output/pipeline-token') | b64encode }}"
        INFLUX_URL: "{{ 'https://database.placebo-pharma.com:8086' | b64encode }}"
  tags:
    - services
    - pipeline

- name: Pipeline Grapher InfluxDB read credentials
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: influxdb-grapher
        namespace: pipeline
      data:
        INFLUX_BUCKET: "{{ 'PlaceboPharmaData' | b64encode }}"
        INFLUX_ORG: "{{ 'PlaceboPharma' | b64encode }}"
        INFLUXDB_TOKEN: "{{ lookup('file', '../../pre/database/output/data-science-token') | b64encode }}"
        INFLUX_URL: "{{ 'https://database.placebo-pharma.com:8086' | b64encode }}"
  tags:
    - services
    - pipeline

- name: Deploy pipeline resources
  become: true
  become_user: ubuntu
  kubernetes.core.k8s:
    state: present
    src: "/home/ubuntu/pipeline/{{ item }}"
  loop:
    - etcher/configmap.yaml
    - etcher/deployment.yaml
    - etcher/ingress.yaml
    - etcher/service.yaml
    - grapher/configmap.yaml
    - grapher/deployment.yaml
    - grapher/ingress.yaml
    - grapher/service.yaml
    - recorder/configmap.yaml
    - recorder/deployment.yaml
    - recorder/ingress.yaml
    - recorder/rbac.yaml
    - recorder/service.yaml
  tags:
    - services
    - pipeline
